apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin:latest
        imagePullPolicy: Never
        resources:
          limits:
            memory: "256Mi"
          requests:
            memory: "64Mi"
        ports:
        - containerPort: 5000
          name: phpmyadmin
