apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:latest
        imagePullPolicy: Never
        resources:
          limits:
            memory: "384Mi"
          requests:
            memory: "128Mi"
        ports:
        - containerPort: 5050
          name: wordpress
        volumeMounts:
        - name: wordpress-storage
          mountPath: /var/www/localhost/htdocs
      volumes:
      - name: wordpress-storage
        persistentVolumeClaim:
          claimName: wordpress-pv-claim
