apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: "shared"
spec:
  type: LoadBalancer
  selector:
    app: ftps
  loadBalancerIP: 192.168.49.242
  ports:
  - port: 21
    name: ftp
  - port: 20021
    name: ftp-data
