apiVersion: v1
kind: Service
metadata:
  name: nginx
  annotations:
    metallb.universe.tf/allow-shared-ip: "shared"
spec:
  type: LoadBalancer
  selector:
    app: nginx
  loadBalancerIP: 192.168.117.242
  ports:
  - port: 22
    name: ssh
  - port: 80
    name: http
  - port: 443
    name: https
