apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  annotations:
    metallb.universe.tf/allow-shared-ip: "shared"
spec:
  type: LoadBalancer
  selector:
    app: phpmyadmin
  loadBalancerIP: 192.168.117.242
  ports:
  - port: 5000
    name: phpmyadmin
