apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: "shared"
spec:
  type: LoadBalancer
  selector:
    app: wordpress
  loadBalancerIP: 192.168.49.242
  ports:
  - port: 5050
    name: wordpress
