# create service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: telegraf
---
# bind service account to cluster role
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metrics:reader
subjects:
- kind: ServiceAccount
  name: telegraf
  namespace: default
roleRef:
  kind: ClusterRole
  name: metrics
  apiGroup: rbac.authorization.k8s.io
