{
 "title": "Kubernetes Pods and Node",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "total_mem",
    "query": "SELECT last(\"total\") FROM \"mem\""
   },
   {
    "name": "total_cores",
    "query": "SELECT last(\"n_cpus\") FROM \"docker\""
   }
  ]
 },
 "panels": [
  {
   "title": "Pods memory and CPU Graphs (default namespace)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kubernetes_pod_container",
     "select": [
      [
       { "params": [ "memory_usage_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 1024 / 1024" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "namespace", "operator": "=", "value": "default" }
     ]
    }
   ]
  },
  {
   "title": "CPU Cores Usage%",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kubernetes_pod_container",
     "select": [
      [
       { "params": [ "cpu_usage_nanocores" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 1000000000 / $total_cores" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "namespace", "operator": "=", "value": "default" }
     ]
    }
   ]
  },
  {
   "title": "Pods Network (default namespace)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 }
  },
  {
   "title": "Bytes received",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "kubernetes_pod_network",
     "query": "SELECT max(\"rx_bytes\") FROM \"docker_container_net\" WHERE (\"io.kubernetes.container.name\" = 'nginx') AND $timeFilter GROUP BY time(10m) fill(0)",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "namespace", "operator": "=", "value": "default" }
     ]
    }
   ]
  },
  {
   "title": "Receive errors",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "kubernetes_pod_network",
     "query": "SELECT max(\"rx_bytes\") FROM \"docker_container_net\" WHERE (\"io.kubernetes.container.name\" = 'nginx') AND $timeFilter GROUP BY time(10m) fill(0)",
     "select": [
      [
       { "params": [ "rx_errors" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "namespace", "operator": "=", "value": "default" }
     ]
    }
   ]
  },
  {
   "title": "Bytes transfered",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "kubernetes_pod_network",
     "query": "SELECT max(\"rx_bytes\") FROM \"docker_container_net\" WHERE (\"io.kubernetes.container.name\" = 'nginx') AND $timeFilter GROUP BY time(10m) fill(0)",
     "select": [
      [
       { "params": [ "tx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "namespace", "operator": "=", "value": "default" }
     ]
    }
   ]
  },
  {
   "title": "Transfer errors",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 17, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "kubernetes_pod_network",
     "query": "SELECT max(\"rx_bytes\") FROM \"docker_container_net\" WHERE (\"io.kubernetes.container.name\" = 'nginx') AND $timeFilter GROUP BY time(10m) fill(0)",
     "select": [
      [
       { "params": [ "tx_errors" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "namespace", "operator": "=", "value": "default" }
     ]
    }
   ]
  },
  { "title": "Node memory and CPU Graphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kubernetes_node",
     "select": [
      [
       { "params": [ "memory_usage_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1024 / 1024" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Cores Usage%",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kubernetes_node",
     "select": [
      [
       { "params": [ "cpu_usage_nanocores" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000000000 / $total_cores" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  { "title": "Node Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Bytes received",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "kubernetes_node",
     "query": "SELECT max(\"rx_bytes\") FROM \"docker_container_net\" WHERE (\"io.kubernetes.container.name\" = 'nginx') AND $timeFilter GROUP BY time(10m) fill(0)",
     "select": [
      [
       { "params": [ "network_rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "node_name", "operator": "=", "value": "minikube" }
     ]
    }
   ]
  },
  {
   "title": "Receive errors",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "kubernetes_node",
     "query": "SELECT max(\"rx_bytes\") FROM \"docker_container_net\" WHERE (\"io.kubernetes.container.name\" = 'nginx') AND $timeFilter GROUP BY time(10m) fill(0)",
     "select": [
      [
       { "params": [ "network_rx_errors" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bytes transfered",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "kubernetes_node",
     "query": "SELECT sum(\"network_tx_bytes\") FROM \"kubernetes_node\" WHERE $timeFilter GROUP BY time(10s) fill(0)",
     "select": [
      [
       { "params": [ "network_tx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "node_name", "operator": "=", "value": "minikube" }
     ]
    }
   ]
  },
  {
   "title": "Transfer errors",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 17, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "kubernetes_node",
     "query": "SELECT max(\"rx_bytes\") FROM \"docker_container_net\" WHERE (\"io.kubernetes.container.name\" = 'nginx') AND $timeFilter GROUP BY time(10m) fill(0)",
     "select": [
      [
       { "params": [ "network_tx_errors" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  }
 ]
}