{
 "title": "Telegraf",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "service", "query": "telegraf" },
   {
    "name": "mem_limit",
    "query": "SELECT last(\"limit\") FROM \"docker_container_mem\" WHERE (\"io.kubernetes.container.name\" = '$service')"
   },
   {
    "name": "total_cores",
    "query": "SELECT last(\"n_cpus\") FROM \"docker\""
   }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU usage%",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "io.kubernetes.container.name", "operator": "=", "value": "$service" }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage%",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "io.kubernetes.container.name", "operator": "=", "value": "$service" }
     ]
    }
   ]
  },
  {
   "title": "Kubernetes Cores Usage%",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kubernetes_pod_container",
     "select": [
      [
       { "params": [ "cpu_usage_nanocores" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000000000 / $total_cores" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "container_name", "operator": "=", "value": "$service" }
     ]
    }
   ]
  },
  {
   "title": "Started at",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_status",
     "select": [
      [
       { "params": [ "started_at" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "io.kubernetes.container.name", "operator": "=", "value": "$service" }
     ]
    }
   ]
  },
  {
   "title": "Runtime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_status",
     "select": [
      [
       { "params": [ "uptime_ns" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "io.kubernetes.container.name", "operator": "=", "value": "$service" }
     ]
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Memory usage%",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kubernetes_pod_container",
     "select": [
      [
       { "params": [ "memory_usage_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / $mem_limit * 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "container_name", "operator": "=", "value": "$service" }
     ]
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kubernetes_pod_container",
     "select": [
      [
       { "params": [ "memory_usage_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1024 / 1024" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "container_name", "operator": "=", "value": "$service" }
     ]
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kubernetes_pod_container",
     "select": [
      [
       { "params": [ "memory_usage_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1024 / 1024" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "container_name", "operator": "=", "value": "$service" }
     ]
    }
   ]
  },
  {
   "title": "Memory Usage%",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kubernetes_pod_container",
     "query": "SELECT mean(\"memory_usage_bytes\")  / $mem_limit * 100 FROM \"kubernetes_pod_container\" WHERE (\"container_name\" = '$service') AND $timeFilter GROUP BY time(10s) fill(null)",
     "select": [
      [
       { "params": [ "memory_usage_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / $mem_limit * 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "container_name", "operator": "=", "value": "$service" }
     ]
    }
   ]
  },
  {
   "title": "Memory limit",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 5, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_mem",
     "select": [
      [
       { "params": [ "limit" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1024 / 1024" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "io.kubernetes.container.name", "operator": "=", "value": "$service" }
     ]
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Bytes received",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "docker_container_net",
     "query": "SELECT max(\"rx_bytes\") FROM \"docker_container_net\" WHERE (\"io.kubernetes.container.name\" = 'nginx') AND $timeFilter GROUP BY time(10m) fill(0)",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "io.kubernetes.container.name", "operator": "=", "value": "$service" }
     ]
    }
   ]
  },
  {
   "title": "Packets received",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 5, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "docker_container_net",
     "query": "SELECT max(\"rx_bytes\") FROM \"docker_container_net\" WHERE (\"io.kubernetes.container.name\" = 'nginx') AND $timeFilter GROUP BY time(10m) fill(0)",
     "select": [
      [
       { "params": [ "rx_packets" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "io.kubernetes.container.name", "operator": "=", "value": "$service" }
     ]
    }
   ]
  },
  {
   "title": "Receive errors",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 11, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "docker_container_net",
     "query": "SELECT max(\"rx_bytes\") FROM \"docker_container_net\" WHERE (\"io.kubernetes.container.name\" = 'nginx') AND $timeFilter GROUP BY time(10m) fill(0)",
     "select": [
      [
       { "params": [ "rx_errors" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "io.kubernetes.container.name", "operator": "=", "value": "$service" }
     ]
    }
   ]
  },
  {
   "title": "Receive packets dropped",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 15, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "docker_container_net",
     "query": "SELECT max(\"rx_bytes\") FROM \"docker_container_net\" WHERE (\"io.kubernetes.container.name\" = 'nginx') AND $timeFilter GROUP BY time(10m) fill(0)",
     "select": [
      [
       { "params": [ "rx_dropped" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "io.kubernetes.container.name", "operator": "=", "value": "$service" }
     ]
    }
   ]
  },
  {
   "title": "Bytes transfered",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "docker_container_net",
     "query": "SELECT max(\"rx_bytes\") FROM \"docker_container_net\" WHERE (\"io.kubernetes.container.name\" = 'nginx') AND $timeFilter GROUP BY time(10m) fill(0)",
     "select": [
      [
       { "params": [ "tx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "io.kubernetes.container.name", "operator": "=", "value": "$service" }
     ]
    }
   ]
  },
  {
   "title": "Packets transfered",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 5, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "docker_container_net",
     "query": "SELECT max(\"rx_bytes\") FROM \"docker_container_net\" WHERE (\"io.kubernetes.container.name\" = 'nginx') AND $timeFilter GROUP BY time(10m) fill(0)",
     "select": [
      [
       { "params": [ "tx_packets" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "io.kubernetes.container.name", "operator": "=", "value": "$service" }
     ]
    }
   ]
  },
  {
   "title": "Transfer errors",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 11, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "docker_container_net",
     "query": "SELECT max(\"rx_bytes\") FROM \"docker_container_net\" WHERE (\"io.kubernetes.container.name\" = 'nginx') AND $timeFilter GROUP BY time(10m) fill(0)",
     "select": [
      [
       { "params": [ "tx_errors" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "io.kubernetes.container.name", "operator": "=", "value": "$service" }
     ]
    }
   ]
  },
  {
   "title": "Transfer packets dropped",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 15, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "docker_container_net",
     "query": "SELECT max(\"rx_bytes\") FROM \"docker_container_net\" WHERE (\"io.kubernetes.container.name\" = 'nginx') AND $timeFilter GROUP BY time(10m) fill(0)",
     "select": [
      [
       { "params": [ "tx_dropped" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "io.kubernetes.container.name", "operator": "=", "value": "$service" }
     ]
    }
   ]
  }
 ]
}